apiVersion: v1
kind: Pod
metadata:
   name: autograder-pod
   labels:
    app: autograder
spec:
   containers:
   - name: autograder-container
     image: mahshaban95/autograder-jenkins:20
     ports:
     - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: autograder-service
spec:
  type: NodePort
  selector:
    app: autograder
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30001
